###配置服务端口
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
  instance:
    hostname: localhost
    appname: xiaomo-gateway
    instance-id: sh_xiaomo_gateway
    prefer-ip-address: true
spring:
  application:
    name: gateway-cloud5002
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: baidu
          uri: http://localhost:8761/
          predicates:
            - Path=/baidu/**
          filters:
            - StripPrefix=1



        - id: sina
          uri: http://movie.hs6356.com/
          predicates:
            - Path=/sina/**
          filters:
            - StripPrefix=1
org:
  my:
    jwt:
      #跳过认证的路由
      skip-auth-urls:
        - /auth/**
      ############################################
      #   有效时长
      #     单位：d:天、h:小时、m:分钟、s:秒
      ###########################################
      effective-time: 3m
