###配置服务端口
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
  instance:
    hostname: localhost
    appname: xiaomo-gateway
    instance-id: sh-xiaomo-gateway
    prefer-ip-address: true
spring:
  application:
    name: gateway-cloud5002
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.4:3306/sh_xiaomo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xiaomo
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: sh_cloud_server
          #uri: lb://sh-cloud-server
          uri: http://localhost:8082
          predicates:
          - Path=/auth/**
          filters:
            - StripPrefix=0 #去掉Path中前0个节点
            - name: Retry
              args:
                retries: 1 #重试次数
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: "ALWAYS"
org:
  my:
    jwt:
      #跳过认证的路由
      skip-auth-urls:
        - /auth/**
      ############################################
      #   有效时长
      #     单位：d:天、h:小时、m:分钟、s:秒
      ###########################################
      effective-time: 3m
