server:
  port: 8081
swagger:
  base-package: com.xiaomo.wpp.controller
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
  instance:
    hostname: localhost
    appname: xiaomo-authority
    instance-id: sh_xiaomo_auth
    prefer-ip-address: true
## 数据库配置参数
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.93.171:3306/wpp001?useUnicode=true&characterEncoding=utf-8
    username: root
    password: XiaoMo@2020
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml # 配置映射文件地址
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
